package ssh

import (
	"fmt"
	"html/template"
	"log"
	"os"
	"time"

	"github.com/Xuanwo/tiresias/constants"
	"github.com/Xuanwo/tiresias/model"
	"github.com/Xuanwo/tiresias/utils"
)

const sshConfigTemplate = `Host {{ .Name }}
    HostName {{ .Address }}
    {{- if .User }}
    User {{ .User }}
    {{- end }}
    {{- if .Port }}
    Port {{ .Port }}
    {{- end }}
    {{- if .IdentityFile }}
    IdentityFile {{ .IdentityFile }}
    {{- end }}

`

// SSH is used to update SSH Config
type SSH struct {
	Path string `yaml:"path"`

	tmpl *template.Template
	fd   *os.File
}

// Init will initiate SSH.
func (ss *SSH) Init() (err error) {
	// Init template.
	ss.tmpl, err = template.New("ssh_config").Parse(sshConfigTemplate)
	if err != nil {
		return
	}

	// Init ssh config.
	ss.fd, err = os.OpenFile(ss.Path, os.O_RDWR|os.O_CREATE, 0600)
	if err != nil {
		log.Fatal(err)
	}

	// Seek to the start point of last update.
	cur, err := utils.Seek(ss.fd)
	if err != nil {
		log.Fatal(err)
	}
	err = ss.fd.Truncate(cur)
	if err != nil {
		log.Fatal(err)
	}
	_, err = ss.fd.WriteString(fmt.Sprintf("%sGenerated by %s at %s%s\n",
		constants.CommentPrefix, constants.Name, time.Now(), constants.CommentSuffix))
	if err != nil {
		log.Fatal(err)
	}

	return
}

// Close write will close resource that used.
func (ss *SSH) Close() error {
	return ss.fd.Close()
}

// Write will write servers into ssh config.
func (ss *SSH) Write(c chan *model.Server) (err error) {
	for v := range c {
		err = ss.tmpl.Execute(ss.fd, v)
		if err != nil {
			log.Printf("Template generate failed for %v", err)
			continue
		}
	}

	return
}
